@startuml
scale 2/3
!include Interpreter.puml
!include Literal.puml
!include Parser.puml
!include Lexer.puml
!include Token.puml

SymbolTable::table *-- Literal : contains many
Interpreter *-- Parser : creates one
Interpreter *-- Lexer : creates one

@enduml