@startuml
scale 2/3
!include Interpreter.puml
!include Parser.puml
!include Lexer.puml

abstract class Literal


SymbolTable::table *-- Literal : contains many
Interpreter *-- Parser : creates one
Interpreter *-- Lexer : creates one

@enduml